version: "3.7"
services:

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"


  flower:
    container_name: flower

    command: celery -A src.hashing_worker.worker:celery flower --port=5555
    restart: always

    build:
      context: .
      dockerfile: docker/api/Dockerfile

    ports:
      - 5555:5555

    depends_on:
      - redis
      - celery_worker