version: "3.7"
services:

  redis:
    container_name: redis
    restart: always

    build:
      context: .
      dockerfile: docker/redis/Dockerfile

    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"


  postgres:
    container_name: postgresql
    restart: always

    build:
      context: .
      dockerfile: docker/postgres/Dockerfile

    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "${DB_PORT}:${DB_PORT}"


  upload_api:
    container_name: upload_api

    command: uvicorn src.ui_service.main:app --host "0.0.0.0" --port ${API_PORT}
    restart: always

    build:
      context: .
      dockerfile: docker/api/Dockerfile

    volumes:
      - &appdata_folder ./appdata:/appdata

    depends_on:
      - postgres
      - redis

    ports:
      - "${API_PORT}:${API_PORT}"


  celery_worker:

    command: celery -A src.md5_service.worker:celery worker --loglevel=INFO
    restart: always
    deploy:
      mode: replicated
      replicas: 2

    build:
      context: .
      dockerfile: docker/api/Dockerfile

    volumes:
      - *appdata_folder

    depends_on:
      - redis
      - postgres
